# Site settings
title: Chris Basinger
email: zerochancelabs@atomicmail.io
url: https://github.com/jeromelachaud/freelancer-theme
description: "I’m a self-taught Android developer with over 10 years of experience building apps independently. I’m a highly motivated, goal-oriented, selfless leader that is driven by a strong passion for creating Android apps with the latest technologies.

I fully immerse myself in different types of fitness, sports, meditation, and martial arts while I develop mobile apps for them."
keywords: "kotlin,ktor,android developer,android development,exposed,coroutines,java"
skills: "Android Developer"
meta_author: Basinger Chris

plugins:
  - jekyll-remote-theme

remote_theme: jeromelachaud/freelancer-theme

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5B6E8C
  primary-rgb: "91, 110, 140"
  secondary: C4A882
  secondary-dark: A0845A

# Footer settings
footer:
  copyright: Chris Basinger
  location: Rockwall, Texas
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: strava
    url: https//strava.app.link/Mcwf7mv1k2b
  - title: instagram
    url: https://instagram.com/trailguy1990

# Postal address (add as many lines as necessary)
address:
  - line: Zero Chance Labs
  - line: Rockwall, TX 75087

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
