# Site settings
title: Chris Basinger
email: evilthreads666@atomicmail.io
url: https://github.com/jeromelachaud/freelancer-theme
description: "My name is Chris Basinger and I am an Android developer who lives in Rockwall, Texas."
keywords: "kotlin,ktor,android developer,android development,exposed,coroutines,java"
skills: "Android Developer"
meta_author: Basinger Chris

plugins:
  - jekyll-remote-theme

remote_theme: jeromelachaud/freelancer-theme

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5B6E8C
  primary-rgb: "91, 110, 140"
  secondary: C4A882
  secondary-dark: A0845A

# Footer settings
footer:
  copyright: Chris Basinger
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: strava
    url: https://strava.app.link/Mcwf7mv1k2b
  - title: instagram
    url: https://instagram.com/trailguy1990
  - title: linkedin
    url: https://www.linkedin.com/in/chris-basinger-91207b403/

# Postal address (add as many lines as necessary)
address:
  - line: Zero Chance Labs
  - line: Rockwall, TX 75087

# Build settings
markdown: kramdown
permalink: pretty

collections:
  updates:
    output: true

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

